@startuml
left to right  direction
newActor -- (Identificarse)
newActor  -- (Pagar)
newActor  -- (Elegir mensajero)
newActor  -- (Confirmar)
(Identificarse) <|.. (Registrarse) : <<extend>>
(Pagar) <|--  (Pagar con tarjeta)
(Pagar) <|-- (Pagar con transferencia)
@enduml