@startuml

usecase UC1 as "Sacar dinero
--
+ solicitud hecha
"
(Retener tarjeta) ..|> UC1
note "Description\ncondición:\n\t{historia sospechosa}\npunto de extensión:\n\tsolicitud hecha" as n1
(Retener tarjeta) - n1

@enduml